# Generated by Django 4.1.2 on 2023-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email_address')),
                ('role', models.CharField(max_length=20)),
                ('company_id', models.CharField(max_length=30, null=True)),
                ('status', models.BooleanField(default=True)),
                ('password', models.CharField(default='password123', max_length=20)),
            ],
        ),
    ]
