class jsonkey:
    def __init__(self):
        self.thisdict = {
            "PatientInitials": ["PATIENTINITIALS", "1.PATIENT INITIALS", 'PATIENT INITIALS', 'L.PATIENT INITIALS',
                                '1.PATIENT INITIALS'],
            "Country": ['COUNTRY', '1a.COUNTRY', 'COUNTRY', 'la.COUNTRY'],
            "DescribeReaction": ['DESCRIBE REACTION(S)', '7+13DESCRIBE REACTION(S)', '7+13 DESCRIBE REACTION(S)',
                                 '7.+13. DESCRIBE REACTION(S)',
                                 '7 + 13 DESCRIBE REACTION(S)', '7.413. DESCRIBE REACTION(S)',
                                 '7+13. DESCRIBE REACTION(S)'],
            "DateOfBirth": ['2.DATE OF BIRTH', ],
            "Day_DOB": [''],
            "Month_DOB": [''],
            "Year_DOB": [''],
            "Age": ['2a. AGE', 'AGE', '2a. AGE', '2a.AGE'],
            "Sex": ['3.8SEX', '3.SEX', 'SEX'],
            "Height": ['HEIGHT', '3.a'],
            "Weight": ['3a. WEIGHT', 'WEIGHT'],
            "Reaction_onset": ['4-6 REACTION ONSET'],
            "Day_ReactionOnset": [''],
            "Month_ReactionOnset": [''],
            "Year_ReactionOnset": [''],
            "DateOfConsequence_Day": [''],
            "DateOfConsequence_Month": [''],
            "DateOfConsequence_Year": [''],
            "Consequence": ['CONSEQUENCE'],
            "SuspectDrug": ['SUSPECT DRUG(S)', '14.SUSPECT DRUG(S)', 'medicinalproduct', '14. SUSPECT DRUG(S)(include',
                            '14. SUSPECT DRUG(S)'],
            "SuspectDrug2": ['SUSPECTDRUG2'],
            "DailyDose": ['DAILY DOSE(S)', '15.DAILY DOSE(S)', '15. DAILY DOSE(S)', '15. DAILY DOSE',
                          '15. DAILY DOSE(S).'],
            "RouteOfAdministration": ['16. ROUTE(S) OF ADMINISTRATION', 'ROUTE(S) OF ADMINISTRATION',
                                      '16. ROUTE(S) OF ADMINISTRATION', '16. ROUTE OF ADMINISTRATION',
                                      '16. ROUTE(S) OF ADMINISTRATION.', '16. ROUTE(S) OF ADMINISTRATION,'],
            "IndicationForUse": ['INDICATIONFORUSE', '17.INDICATIONFORUSE', '17. INDICATION(S) FOR USE',
                                 '17. INDICATIONS) FOR USE', '17. INDICATIONS FOR USE', '17. INDICATION(S} FOR USE'],
            "IndicatonForUse2": ['INDICATONFORUSE2'],
            "TherapyDatesFromTo": ['THERAPYDATESFROMTO', '18.THERAPYDATESFROMTO', '18. THERAPY DATES(from/to)',
                                   '18. THERAPY DATES(fronvto)', '18. THERAPY DATES (from/to)',
                                   '18. THERAPY DATES(FronvTo)', '18. THERAPY DATES(From/To)',
                                   '18. THERAPY DATES(fromito)'],
            "TherapyDuration": ['THERAPYDURATION', '19.THERAPYDURATION', '19. THERAPY DURATION', 'THERAPY DURATION'],
            "OneTimeDose": ['ONETIMEDOSE'],
            "LotNo": ['LOTNO'],
            "ConcomitantDrugs": ['CONCOMITANTDRUGS', '22.CONCOMITANT', 'CONCOMITANT'],
            "OtherRelevantHistory": ['OTHERRELEVANTHISTORY', '23. OTHER RELEVANT HISTORY',
                                     '23. OTHER RELEVANT HISTORY.'],
            "NameAndAddresManufacturer": ['NAMEANDADDRESMANUFACTURER', '24a.NAME AND ADDRESS OF MANUFACTURER'],
            "MFRControlNo": ['MFRCONTROLNO', '24b.MFR CONTROL NO', 'MFR CONTROL NO.'],
            "Date_Received_Manufacturer": ['DATE_RECEIVED_MANUFACTURER', '24c.DATE RECEIVED MANUFACTURER',
                                           '24c. DATE RECEIVED', '24. DATE RECEIVED.', '24c, DATE RECEIVED',
                                           '24c. DATE RECEIVED BY MANUFACTURER', '24c. DATE RECEIVED BY MANUFACTURER',
                                           '24c. DATE RECEIVED BY MANUFACTURER', '24c. DATE RECEIVED',
                                           '24c. DATE RECEIVED.'],
            "Date_This_Report": ['DATE THIS REPORT', 'DATE OF THIS REPORT'],
            "ReporterInformation": ['REPORTERINFORMATION', '25b. NAME AND ADDRESS OF REPORTER'],
            "EudraCTNo": ['EUDRACTNO'],
            "StudyNo": ['STUDYNO'],
            "CenterNo": ['CENTERNO'],
            "FileName": ['FileName'],
            "VendorName": ['VendorName'],
            "Reaction Information ( Cont...)": ['REACTION INFORMATION', 'primarysourcereaction',
                                                'Reaction Information ( Cont...)'],
            "Describe Reaction(s)(Include relevant test/lab data) ( Cont...)": ['DESCRIBE REACTION(S)',
                                                                                '7+13. DESCRIBE REACTION(S) continued',
                                                                                '7.413. DESCRIBE REACTION(S)'],
            "Suspect Drugs (Cont...)": ['SUSPECT DRUGS', 'Suspect Drugs (Cont...)', 'Suspect Products (Cont...)'],
            "Concomitant drugs (Cont ...)": ['CONCOMITANT DRUGS', 'Concomitant drugs (Cont...)',
                                             'Concomitant drugs (Cont ...)', 'Concomitant Drugs (Cont ...)'],
            "Other relevant history (Cont...)": ['Other relevant history (Cont...)'],
            "Company Remarks (Sender's comments)(Cont...)": ["COMPANY REMARKS (SENDER'S COMMENTS)"],
            "Literature Information (Cont...)": ['LITERATURE INFORMATION (CONT...)'],
            "Additional Information(Continuation)": ['ADDITIONAL INFORMATION(CONTINUATION)'],
            "reportertitle": ["reportertitle"],
            "reporterpostcode": ["reporterpostcode"],
            "reporterstate": ["reporterstate", "REPORTERSTATE"],
            "reportercity": ["reportercity"],
            "reporterstreet": ["reporterstreet"],
            "reporterdepartment": ["reporterdepartment"],
            "reporterorganization": ["reporterorganization"],
            "reporterfamilyname": ["reporterfamilyname"],
            "qualification": ["qualification"],
            "companynumb": ["companynumb"],
            "ReactionInformation": ['ReactionInformation'],
            "PatientDied": ["PatientDied", "PATIENT DIED"],
            "InvolvedOrProlongedInpatientHospitalisation": ["INVOLVED OR PROLONGED INPATIENT HOSPITALIZATION",
                                                            "INVOLVED OR PROLONGED INPATIENT HOSPITALIZATION"],
            "InvolvedPersistentOrSignificantDisabilityOrIncapacity": [
                "INVOLVED PERSISTENT OR SIGNIFICANT DISABILITY OR INCAPACITY",
                "INVOLVED PERSISTENCE OR SIGNIFICANT DISABILITY OR INCAPACITY"],
            "LifeThreatening": ["LIFE THREATENING"],
            "CongenitalAnomaly": ["CONGENITAL ANOMALY", "CONGENITAL ANOMALY / BIRTH DEFECT"],
            "OtherMedeicallyImportantCondition": ["OTHER MEDICALLY IMPORTANT CONDITION"],
            "Study": ["STUDY"],
            "Literature": ["LITERATURE"],
            "HealthProffessional": ["HEALTH PROFESSIONAL"],
            "OtherUnsolicitedNonLiterature": ["OTHER: Unsolicited Non Literature"],
            "Initial": ["INITIAL"],
            "Followup": ["FOLLOWUP"],
            "Authority": ["AUTHORITY"],
            "Other": ["OTHER"],
            "DidReactionAbateAfterStoppingDrug": ["20. DID REACTION ABATE AFTER STOPPING DRUG?",
                                                  "20.DID REACTION ABATE AFTER STOPPING DRUG?"],
            "DidReactionReappearAfterReintroduction": ["21. DID REACTION REAPPEAR AFTER REINTRODUCTION?",
                                                       "21.DID REACTION REAPPEAR AFTER REINTRODUCTION?"],
            "png_data": ['from_png_data']

        }