# json key mapping
class medwatchjsonkey:
    def __init__(self):
        self.thisdict = {
            "PatientInitials": ["1. Patient Identifier"],
            "Country": [],
            "DescribeReaction": ["Describe Event or Problem","5. Describe Event or Problem"],
            "Date_of_Birth": ["Date of Birth:"],
            "Day_DOB": [''],
            "Month_DOB": [''],
            "Year_DOB": [''],
            "Age": ['2. Age at Time','|2. Age at Time'],
            "Sex": ['SEX'],
            "Height": [''],
            "Weight": ['Weight', '4. Weight'],
            "Day_ReactionOnset": [''],
            "Month_ReactionOnset": [''],
            "Year_ReactionOnset": [''],
            "DateOfConsequence_Day": [''],
            "DateOfConsequence_Month": [''],
            "DateOfConsequence_Year": [''],
            "Consequence": [''],
            "DateOfEvent": ['3. Date of Event'],            
            "Date_This_Report": ['4. Date of This Report', 'DATE OF THIS REPORT', 'Date of This Report'],
            "ReleventTest_LadbData": ["Relevant Tests/Laboratory Data, Including Dates","6. Relevant Tests/Laboratory Data, Including Dates"],
            "OtherRelevantHistory": ['Other Relevant History','Other Relevant History, Including Preexisting Medical'],            
            "SuspectDrugName": ["Name (give labeled strength & mfr/labeler)",'1. Name (give labeled strength & mfr/labeler)', "1. Name (Give labeled strength & mfrfabeler)","1. Name (Give labeled strength & mft/abeler)", '1. Name (Give labeled strength & mfrfabeler)'],
            "DailyDose": ['2. Dose, Frequency & Route Used', 'Dose, Frequency'],
            "TherapyDatesFromTo": ['3. Therapy dates',"3. Therapy Dates"],
            "DiagnosisForUse": ['4. Diagnosis','Diagnosis for use'],
            "LotNo": ['6. Lot #'],
            "ExpDate": ['7. Exp. Date'],
            "NdcNoUniqueId": ['9. NDC# or Unique ID'],
            "ConcomitantDrugs": ['10. Concomitant Medical Products and Therapy Dates'],
            "NameAndAddresManufacturer": ['1. Contact Office'],
            "ManufacturerPhoneNumber": ['2. Phone Number'],
            "MFRControlNo": ['9. Manufacturer Report Number'],
            "Date_Received_Manufacturer": ['4. Date Received by', 'Manufacturer (mm/dd/yyyy)'],
            "IndGiveProtocolNo": ["6. If IND, Give Protocol #"],
            "ReporterInformation": ['Name and Address','\"Name and Adress'],
            "AdverseEventTerms": ["8. Adverse Event Term(s)"],
            "Occupation": ['3. Occupation','|3. Occupation'],
            "DescribeReactionContinue": ["B.5. Describe Event or Problem [continued]","B5. EVENT DESCRIPTION"],
            "LabDataContinue": ["B6. LABORATORY DATA", "B.6. Relevant Tests/Laboratory Data","B7. OTHER RELEVANT HISTORY"],
            "OtherRlevantHistoryContinue": ["B.7. Other Relevant History, Including Preexisting Medical Conditions [continued]"],
            "SuspectDrugNameContinue1": ["C.1.#1. Name [continued]"],
            "DailyDoseContinue1": ["C.2.#1. Dose, Frequency & Route Used [continued]"],
            "TherapyDatesFromToContinue1": ["C.3.#1. Therapy Dates [continued]",],
            "SuspectDrugNameContinue2": ["C.1.#2 Name [continued]"],
            "DailyDoseContinue2": ["C.2.#2. Dose, Frequency & Route Used [continued]"],
            "TherapyDatesFromToContinue2": ["C.3.#2. Therapy Dates"],
            "AdverseEventTermsContinue": ["G8. ADVERSE EVENT TERMS", "G.8. Adverse Event Term(s) [continued]"],
            "DiagnosisForUseContinue": ["C4. DIAGNOSIS FOR USE"],
            "ConcomitantDrugsContinue": ["C10. CONCOMITANT MEDICAL PRODUCTS"],
            "Female":["FEMALE","Female"],
            "Male":["MALE","Male"],
            "PatientDied":["Death","outcome_death","Death:"],
            "LifeThreatening":["life_threatening","Life-threatening","outcome_life_threatening"],
            "Hospitalization":["Hospitalization","Hospitalization","outcome_hospitalization"],
            "Disability":["Disability","Disability","outcome_disability"],
            "Congenital":["Congenital","Congenital Anomaly/Birth","outcome_congenital"],
            "OtherSerious":["Other_serious","Other Serious","outcome_other_serious"],
            "RS_foreign":["RS_foreign","Foreign","report_source_foreign"],
            "RS_study":["RS_study","Study","report_source_study"],
            "RS_literature":["RS_literature","Literature","report_source_literature"],
            "RS_consumer":["RS_consumer","Consumer","report_source_consumer"],
            "RS_health_professional":["RS_health_professional","Health Professional","report_source_health_professional"],
            "RS_user_facility":["RS_user_facility","User Facility","report_source_user_facility"],
            "RS_company_representative":["RS_company_representative","Company Representative","report_source_company_representative"],
            "RS_distributor":["RS_distributor","Distributor","report_source_distributor"],
            "RS_other":["RS_other","Other","report_source_other"],
            "tr_7_day":["tr_7_day","7-day","type_of_report_7_day"],
            "tr_15_day":["tr_15_day","15-day","type_of_report_15_day"],
            "Tr_periodic":["Tr_periodic","Periodic","type_of_report_periodic"],
            "tr_initial":["tr_initial","Initial","type_of_report_initial"],
            "tr_follow_up":["tr_follow_up","Follow-up #","type_of_report_follow_up"], 
            "tr_10-day":["10-day","type_of_report_10_day"],
            "tr_5-day":["5-day","type_of_report_5_day"],
            "tr_30-day":["30-day","type_of_report_30_day"],           
            "SuspectDrug2": [],            
            "RouteOfAdministration": ['16. ROUTE(S) OF ADMINISTRATION', 'ROUTE(S) OF ADMINISTRATION',
                                      '16. ROUTE(S) OF ADMINISTRATION','16. ROUTE OF ADMINISTRATION','16. ROUTE(S) OF ADMINISTRATION.','16. ROUTE(S) OF ADMINISTRATION,'],
            "IndicationForUse": ['INDICATIONFORUSE', '17.INDICATIONFORUSE', '17. INDICATION(S) FOR USE',
                                 '17. INDICATIONS) FOR USE','17. INDICATIONS FOR USE'],
            "IndicatonForUse2": ['INDICATONFORUSE2'],
            "TherapyDuration": ['THERAPYDURATION', '19.THERAPYDURATION', '19. THERAPY DURATION', 'THERAPY DURATION'],
            "OneTimeDose": ['ONETIMEDOSE'],            
            "EudraCTNo": [''],
            "StudyNo": [''],
            "CenterNo": [''],
            "FileName": [''],
            "VendorName": [''],
            "Reaction Information ( Cont...)": ['REACTION INFORMATION', 'primarysourcereaction',
                                                'Reaction Information ( Cont...)'],
            "Describe Reaction(s)(Include relevant test/lab data) ( Cont...)": ['DESCRIBE REACTION(S)'],
            "Suspect Drugs (Cont...)": ['SUSPECT DRUGS', 'Suspect Drugs (Cont...)'],
            "Concomitant drugs (Cont ...)": ['CONCOMITANT DRUGS', 'Concomitant drugs (Cont...)',
                                             'Concomitant drugs (Cont ...)', 'Concomitant Drugs (Cont ...)'],
            "Other relevant history (Cont...)": ['Other relevant history (Cont...)'],
            "Company Remarks (Sender's comments)(Cont...)": ["COMPANY REMARKS (SENDER'S COMMENTS)"],
            "Literature Information (Cont...)": ['LITERATURE INFORMATION (CONT...)'],
            "Additional Information(Continuation)": ['ADDITIONAL INFORMATION(CONTINUATION)'],
            "reportertitle": ["reportertitle"],
            "reporterpostcode": ["reporterpostcode"],
            "reporterstate": ["reporterstate", "REPORTERSTATE"],
            "reportercity": ["reportercity"],
            "reporterstreet": ["reporterstreet"],
            "reporterdepartment": ["reporterdepartment"],
            "reporterorganization": ["reporterorganization"],
            "reporterfamilyname": ["reporterfamilyname"],
            "qualification": ["qualification"],
            "companynumb": ["companynumb"],
            "ReactionInformation": ['ReactionInformation']
        }
