# Generated by Django 4.1.2 on 2023-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=90, unique=True)),
                ('company_abrrev', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
