# Generated by Django 4.1.2 on 2023-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=255)),
                ('config_value', models.TextField(blank=True, null=True)),
                ('scope_level', models.CharField(blank=True, max_length=7, null=True)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(fields=('config_key', 'scope_level', 'scope_id'), name='config_values_uidx'),
        ),
    ]
