# Generated by Django 5.0 on 2023-12-22 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 22, 23, 22, 27, 896202), null=True
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 22, 23, 22, 27, 896202), null=True
            ),
        ),
    ]
