# Generated by Django 5.0 on 2023-12-23 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_alter_roles_created_at_alter_roles_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 23, 22, 57, 3, 437983), null=True
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 23, 22, 57, 3, 438984), null=True
            ),
        ),
    ]
