# Generated by Django 5.0 on 2023-12-25 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0005_alter_roles_created_at_alter_roles_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 11, 19, 6, 984732), null=True
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 11, 19, 6, 984732), null=True
            ),
        ),
    ]
