"""dictionary order is according r2xml format"""
r2_mapping = {"case_master_case_version": "safetyreportversion",
              "case_master_case_no": "safetyreportid",
              "case_master_primary_src_country": "primarysourcecountry",
              "case_master_occurance_country": "occurcountry",
              "case_master_report_type": "reporttype",

              "case_summary_serious_reaction": "serious",
              "case_summary_ser_cri_death": "seriousnessdeath",
              "case_summary_ser_cri_life_threat": "seriousnesslifethreatening",
              "case_summary_ser_cri_hospital_pro": "seriousnesshospitalization",
              "case_summary_ser_cri_disability": "seriousnessdisabling",
              "case_summary_ser_cri_cgential_anomaly": "seriousnesscongenitalanomali",
              "case_summary_ser_other": "seriousnessother",

              "case_master_case_init_recv_date": "receivedate",
              "case_master_init_safety_recv_date": "receiptdate",
              "case_master_authority_no": "authoritynumb",
              "case_master_company_no": "companynumb",

              "case_e2b_report_duplicate_duplicate_source": "reportduplicate_duplicatesource",
              "case_e2b_report_duplicate_duplicate_number": "reportduplicate_duplicatenumb",

              "case_linked_report_linked_report_no": "linkedreport_linkreportnumb",

              "case_master_nullify_amend_rep": "casenullification",
              "case_master_reason_for_nullify": "nullificationreason",

              "case_master_medically_confirmed": "medicallyconfirm",

              "case_reporter_salutation": "primarysource_reportertitle",
              "case_reporter_first_name": "primarysource_reportergivename",
              "case_reporter_middle_name": "primarysource_reportermiddlename",
              "case_reporter_last_name": "primarysource_reporterfamilyname",
              "case_reporter_hospital_name": "primarysource_reporterorganization",
              "case_reporter_department": "primarysource_reporterdepartment",
              "case_reporter_street": "primarysource_reporterstreet",
              "case_reporter_city": "primarysource_reportercity",
              "case_reporter_state": "primarysource_reporterstate",
              "case_reporter_postal_code": "primarysource_reporterpostcode",
              "case_reporter_reporter_country": "primarysource_reportercountry",
              "case_reporter_qualification": "primarysource_qualification",

              "case_literature_author": "primarysource_literaturereference",

              "case_study_study_desc": "primarysource_studyname",
              "case_study_sponsor_study_no": "primarysource_sponsorstudynumb",
              "case_study_study_type": "primarysource_observestudytype",

              "case_patient_initials": "patientinitial",
              "case_patient_patient_invgtn_no": "patientinvestigationnumb",
              "case_patient_patient_dob": "patientbirthdate",
              "case_patient_age": "patientonsetage",
              "case_patient_age_unit": "patientonsetageunit",
              "case_patient_gestation_period": "gestationperiod",
              "case_patient_gestation_period_unit": "gestationperiodunit",
              "case_patient_age_group": "patientagegroup",
              "case_patient_weight": "patientweight",
              "case_patient_height": "patientheight",
              "case_patient_gender": "patientsex",
              "case_patient_date_of_LMP": "patientlastmenstrualdate",

              "case_txt_med_history_txt_med_hist": "patientmedicalhistorytext",

              "case_med_history_meddra_llt": "medicalhistoryepisode_patientepisodename",
              "case_med_history_start_date": "patientmedicalstartdate",
              "case_med_history_is_continuing": "medicalhistoryepisode_patientmedicalcontinue",
              "case_med_history_comments": "medicalhistoryepisode_patientmedicalcomment",
              "case_med_history_stop_date": "patientmedicalenddate",
              "case_med_history_meddra_version": "medicalhistoryepisode_patientepisodenamemeddraversion",

              "case_past_drug_history_drug_hist_rpt": "patientpastdrugtherapy_patientdrugname",
              "case_past_drug_history_ind_start_date": "patientpastdrugtherapy_patientdrugstartdate",
              "case_past_drug_history_ind_stop_date": "patientpastdrugtherapy_patientdrugenddate",
              "case_past_drug_history_lab_data_version": "patientpastdrugtherapy_patientindicationmeddraversion",
              "case_past_drug_history_lab_data_llt": "patientpastdrugtherapy_patientdrugindication",
              "case_past_drug_history_rectn_meddra_version": "patientpastdrugtherapy_patientdrgreactionmeddraversion",
              "case_past_drug_history_rectn_meddra_llt": "patientpastdrugtherapy_patientdrugreaction",
              
              
              "case_reaction_death_info_death_date": "patientdeath_patientdeathdate",
              "case_reaction_death_info_is_autopsy_done": "patientdeath_patientautopsyyesno",
              "case_reaction_death_cause_death_caus_medr_ver": "patientdeathcause_patientdeathreportmeddraversion",
              "case_reaction_death_cause_death_cause_llt": "patientdeathcause_patientdeathreport",
              "case_reaction_autopsy_death_autopsy_death_llt": "patientautopsy_patientdetermineautopsy",

              "case_patient_parent_dob": "parentbirthdate",
              "case_patient_p_age": "parentage",
              "case_patient_p_age_unit": "parentageunit",
              "case_patient_p_weight": "parentweight",
              "case_patient_p_height": "parentheight",
              "case_patient_p_gender": "parentsex",
              "case_patient_p_date_of_LMP": "parentlastmenstrualdate",
              
              "case_reaction_reaction_reported": "primarysourcereaction",
              "case_reaction_reaction_coded_version": "reactionmeddraversionllt",
              "case_reaction_reaction_coded_llt": "reactionmeddrallt",
              "case_reaction_reaction_coded_pt": "reactionmeddrapt",
              "case_reaction_term_highlight_rptr": "termhighlighted",
              "case_reaction_reaction_start_date": "reactionstartdate",
              "case_reaction_reaction_end_date": "reactionenddate",
              "case_reaction_reaction_duration": "reactionduration",
              "case_reaction_reaction_unit": "reactiondurationunit",
              "case_reaction_reaction_outcome": "reactionoutcome",
              "case_lab_data_info_test_date": "test_testdate",
              "case_lab_data_info_lab_meddra_llt": "test_testname",
              "case_lab_data_info_test_result_value": "test_testresult",
              "case_lab_data_info_test_result_units": "test_testunit",
              "case_lab_data_info_normal_low_range": "test_lowtestrange",
              "case_lab_data_info_normal_high_range": "test_hightestrange",
              
              "case_product_char_of_product": "drugcharacterization",
              "case_product_product_name": "medicinalproduct",
              "case_product_formulation": "drugdosageform",
              "case_product_country_obtained": "obtaindrugcountry",
              "case_product_drug_authorization_country": "drugauthorizationcountry",
              "case_product_cum_rectn_unit": "drugcumulativedosageunit",
              "case_product_gest_expsre_unit": "reactiongestationperiodunit",
              "case_product_gest_prd_tim_expsre": "reactiongestationperiod",
              "case_product_cum_dos_first_rectn": "drugcumulativedosagenumb",
              "case_product_ma_holder": "drugauthorizationholder",
              "case_product_drug_authorization_number": "drugauthorizationnumb",
              "case_product_action_with_prod": "actiondrug",
              "case_product_product_addl_info": "drugadditional",
              "case_product_indication_coded_llt": "drugindication",
              "case_product_duration_of_regimen": "drugtreatmentduration",
              "case_product_act_sub_name": "activesubstancename",
              "case_product_units": "drugtreatmentdurationunit",
              
              "case_causality_reactiontime_intrvl_begn_admin": "drugstartperiod",
              "case_causality_reactiontime_intrvl_begn_admin_unit": "drugstartperiodunit",
              "case_causality_reactiontime_intrvl_last_dose_unit": "druglastperiodunit",
              "case_causality_time_intrvl_last_dose": "druglastperiod",
              "case_causality_reactionrechallenge": "drugrecurreadministration",

              "case_causality_reaction_rechallenge": "drugrecurreadministration",

              "case_prod_dosage_regimen_dose": "drugstructuredosagenumb",
              "case_prod_dosage_regimen_dose_units": "drugstructuredosageunit",
              "case_prod_dosage_regimen_dosage_text": "drugdosagetext",
              "case_prod_dosage_regimen_patient_roa": "drugadministrationroute",
              "case_prod_dosage_regimen_parent_roa": "drugparadministration",
              "case_prod_dosage_regimen_batch_lot_no": "drugbatchnumb",
              
              }

r2_mapping_date_format = {"receivedate": "receivedateformat",
                          "receiptdate": "receiptdateformat",
                          "patientbirthdate": "patientbirthdateformat",
                          "patientlastmenstrualdate": "lastmenstrualdateformat",
                          "patientmedicalstartdate": "patientmedicalstartdateformat",
                          "patientmedicalenddate": "patientmedicalenddateformat",
                          "patientdrugstartdate" : "patientdrugstartdateformat",
                          "patientdrugenddate":"patientdrugenddateformat",
                          "patientdeathdate":"patientdeathdateformat",
                          "parentbirthdate":"parentbirthdateformat",
                          "parentlastmenstrualdate":"parentlastmenstrualdateformat",
                          "reactionstartdate":"reactionstartdateformat",
                          "reactionenddate":"reactionenddateformat",
                          "drugstartdate":"drugstartdateformat",
                          "drugenddate":"drugenddateformat",
                          }
