# Generated by Django 4.1.2 on 2023-12-21 10:46

from django.db import migrations, models
import ner_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NERTrainingFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.FileField(max_length=500, null=True, upload_to=ner_management.models.get_upload_file_path)),
                ('original_file_name', models.CharField(max_length=500, null=True)),
                ('file_uploaded_type', models.CharField(max_length=500, null=True)),
                ('file_format', models.CharField(max_length=500, null=True)),
                ('file_size', models.CharField(max_length=50, null=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ner_training_files',
            },
        ),
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('ts_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_status', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ner_training_status',
            },
        ),
    ]
